[package]
name = "actix-docker"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true
opt-level = 3
panic = 'abort'
codegen-units = 1

[dependencies]
actix-web = "4.3.1"
serde = { version = "1.0.171", features = ["derive", "rc"] }
serde_json = "1.0.100"
tokio = "1.29.1"
